// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[...stories].tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/stories/[id].tsx";
import * as $$0 from "./islands/Comment.tsx";
import * as $$1 from "./islands/Toggle.tsx";

const manifest = {
  routes: {
    "./routes/[...stories].tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/stories/[id].tsx": $2,
  },
  islands: {
    "./islands/Comment.tsx": $$0,
    "./islands/Toggle.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
